version: '3.7'

services:
  database:
    image: postgres
    container_name: database_tasqcoin
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tasq
      - POSTGRES_PASSWORD=coin
      - POSTGRES_DB=tasqcoin
    volumes:
      - pgdata:/data/postgres
  app:
    environment:
      - NODE_ENV=dev
    build: .
    container_name: tasqcoin-back
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - 'database'
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
